services:
  backend:
    container_name: meu-dash-backend-dev
    image: meu-dash-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    # CORREÇÃO: Aponta o Gunicorn para o novo ponto de entrada 'wsgi:app',
    # que usa a Application Factory de forma segura.
    command: sh -c "gunicorn --workers 4 --bind 0.0.0.0:5000 --reload 'wsgi:app' --chdir /app/backend"
    ports:
      - "${BACKEND_PORT:-5001}:5000"
    volumes:
      - ./backend:/app/backend
      - data-volume:/app/data
      - ./docs:/app/docs
    environment:
      - FLASK_APP=src.app
      - FLASK_DEBUG=True
      - PYTHONPATH=/app/backend
      - FRONTEND_BASE_URL=http://127.0.0.1:${FRONTEND_PORT:-5174}
    env_file:
      - .env

  security-scanner:
    container_name: meu-dash-security-scanner
    image: meu-dash-security-scanner
    build:
      context: .
      dockerfile: backend/Dockerfile.bandit
    volumes:
      - ./backend/src:/app/src

  frontend:
    container_name: meu-dash-frontend-dev
    image: meu-dash-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /app
    ports:
      - "${FRONTEND_PORT:-5174}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  data-volume: