apiVersion: v1
kind: Namespace
metadata:
  name: meu-dash-alertas
---
# Headless service para governar o StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: meu-dash-headless
  namespace: meu-dash-alertas
spec:
  clusterIP: None
  selector:
    app: meu-dash-web
  ports:
  - port: 80
    targetPort: 5000
---
# StatefulSet para fornecer armazenamento estável para cada réplica
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meu-dash-web
  namespace: meu-dash-alertas
spec:
  serviceName: "meu-dash-headless"
  replicas: 2
  selector:
    matchLabels:
      app: meu-dash-web
  template:
    metadata:
      labels:
        app: meu-dash-web
    spec:
      containers:
      - name: meu-dash-web
        image: sevenleo/meu-dash-web:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: meu-dash-data
          mountPath: /app/data
  volumeClaimTemplates:
  - metadata:
      name: meu-dash-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
---
# Service LoadBalancer para acesso externo
apiVersion: v1
kind: Service
metadata:
  name: meu-dash-web
  namespace: meu-dash-alertas
spec:
  type: LoadBalancer
  selector:
    app: meu-dash-web
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meu-dash-web-ingress
  namespace: meu-dash-alertas
spec:
  ingressClassName: nginx
  rules:
  - host: meu-dash-web.devops-master.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: meu-dash-web
            port:
              number: 80