# --- Namespace para organizar os recursos da aplicação ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: smart-remedy

---
# --- ServiceAccount: Define uma identidade dedicada e com privilégios mínimos para a aplicação ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smart-remedy-sa
  namespace: smart-remedy
automountServiceAccountToken: false

---
# --- Headless Service: Necessário para o StatefulSet ---
apiVersion: v1
kind: Service
metadata:
  name: smart-remedy-headless
  namespace: smart-remedy
spec:
  clusterIP: None
  selector:
    app: smart-remedy
  ports:
  - port: 80
    targetPort: http

---
# --- Service ClusterIP: Ponto de acesso interno para o Ingress ---
apiVersion: v1
kind: Service
metadata:
  name: smart-remedy
  namespace: smart-remedy
spec:
  type: ClusterIP
  selector:
    app: smart-remedy
  ports:
  - name: http
    port: 80
    targetPort: http

---
# --- PodDisruptionBudget (PDB): Garante a alta disponibilidade ---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: smart-remedy-pdb
  namespace: smart-remedy
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: smart-remedy

---
# --- StatefulSet: Orquestração dos Pods da aplicação ---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smart-remedy
  namespace: smart-remedy
spec:
  serviceName: "smart-remedy-headless"
  replicas: 1
  selector:
    matchLabels:
      app: smart-remedy
  template:
    metadata:
      labels:
        app: smart-remedy
    spec:
      serviceAccountName: smart-remedy-sa
      automountServiceAccountToken: false

      containers:
      # Contêiner do Nginx: serve o frontend e faz proxy para o backend
      - name: smart-remedy-nginx
        image: sevenleo/smart-remedy:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        command: ["nginx", "-g", "daemon off;"]
        volumeMounts:
        - name: smart-remedy-data
          mountPath: /app/data
        # Recursos ajustados para QoS "Guaranteed" (requests = limits), como no v2
        resources:
          requests:
            cpu: "128m"
            memory: "128Mi"
            ephemeral-storage: "256Mi"
          limits:
            cpu: "128m"
            memory: "128Mi"
            ephemeral-storage: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: http
        livenessProbe:
          httpGet:
            path: /
            port: http

      # Contêiner da API (Gunicorn/Flask): roda a lógica de negócio
      - name: smart-remedy-api
        image: sevenleo/smart-remedy:latest
        imagePullPolicy: Always
        # CORREÇÃO: O ponto de entrada da aplicação é a função create_app()
        # dentro do módulo src.app, e o diretório de trabalho é /app.
        command: ["gunicorn", "--workers", "4", "--bind", "0.0.0.0:5000", "--log-level", "debug", "--access-logfile", "-", "--error-logfile", "-", "src.app:create_app()", "--chdir", "/app"]
        # Variáveis de ambiente no estilo explícito do v2
        env:
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: admin-credentials
              key: ADMIN_USER
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: admin-credentials
              key: ADMIN_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: admin-credentials
              key: SECRET_KEY
        - name: FRONTEND_BASE_URL
          value: "https://smart-remedy.devops-master.shop"
        - name: JWT_EXPIRATION_HOURS
          value: "1"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        # Recursos ajustados para QoS "Guaranteed" (requests = limits), como no v2
        resources:
          requests:
            cpu: "256m"
            memory: "512Mi"
            ephemeral-storage: "256Mi"
          limits:
            cpu: "256m"
            memory: "512Mi"
            ephemeral-storage: "256Mi"
        volumeMounts:
        - name: smart-remedy-data
          mountPath: /app/data
  # CORREÇÃO ERRO 2: Adicionado o storageClassName
  volumeClaimTemplates:
  - metadata:
      name: smart-remedy-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi

---
# --- Ingress: Expõe o serviço para o mundo externo ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smart-remedy-ingress
  namespace: smart-remedy
  annotations:
    # O Ingress Controller NGINX aplicará o certificado wildcard padrão
    # configurado via --default-ssl-certificate.
spec:
  ingressClassName: nginx
  rules:
  - host: smart-remedy.devops-master.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smart-remedy
            port:
              number: 80