# Use uma imagem base do Python 3.12, que é estável e compatível com as ferramentas.
FROM python:3.12-slim-bookworm

# Define o diretório de trabalho dentro do contêiner.
WORKDIR /app

# Instala as dependências do sistema, se houver.
# RUN apt-get update && apt-get install -y ...

# Copia o arquivo de dependências e as instala.
# Isso aproveita o cache do Docker: as dependências só são reinstaladas se o requirements.txt mudar.
COPY ./requirements.txt /app/backend/requirements.txt
RUN pip install --no-cache-dir -r /app/backend/requirements.txt

# O código-fonte será montado por um volume no docker-compose.yml,
# então não precisamos copiá-lo aqui para o ambiente de desenvolvimento.