---
# --- ServiceAccount: Define uma identidade dedicada e com privilégios mínimos para a aplicação ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smart-remedy-sa
  namespace: smart-remedy
automountServiceAccountToken: false

---
# --- Headless Service: Necessário para o StatefulSet ---
apiVersion: v1
kind: Service
metadata:
  name: smart-remedy-headless
  namespace: smart-remedy
spec:
  clusterIP: None
  selector:
    app: smart-remedy
  ports:
  - port: 80
    targetPort: http

---
# --- Service ClusterIP: Ponto de acesso interno para o Ingress ---
apiVersion: v1
kind: Service
metadata:
  name: smart-remedy
  namespace: smart-remedy
spec:
  type: ClusterIP
  selector:
    app: smart-remedy
  ports:
  - name: http
    port: 80
    targetPort: http

---
# --- PodDisruptionBudget (PDB): Garante a alta disponibilidade ---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: smart-remedy-pdb
  namespace: smart-remedy
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: smart-remedy

---
# --- StatefulSet: Orquestração dos Pods da aplicação ---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smart-remedy
  namespace: smart-remedy
spec:
  serviceName: "smart-remedy-headless"
  replicas: 1
  selector:
    matchLabels:
      app: smart-remedy
  template:
    metadata:
      labels:
        app: smart-remedy
    spec:
      # --- Init Container: Executa a migração do banco de dados ANTES dos contêineres principais ---
      initContainers:
      - name: db-migrator
        image: sevenleo/smart-remedy:latest
        imagePullPolicy: Always
        command: ["flask", "db", "upgrade"]
        env:
        - name: FLASK_APP
          value: "wsgi:app" # Aponta para o wsgi.py
        volumeMounts:
        - name: smart-remedy-data
          mountPath: /app/data
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

      serviceAccountName: smart-remedy-sa
      automountServiceAccountToken: false

      # --- Volume compartilhado para o frontend ---
      volumes:
      - name: frontend-dist
        emptyDir: {}

      # --- Contêiner para construir o frontend e copiar para o volume ---
      initContainers:
      - name: frontend-builder
        image: sevenleo/smart-remedy:latest # A imagem já contém o build
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "cp -r /app/src/static/* /frontend-dist/"]
        volumeMounts:
        - name: frontend-dist
          mountPath: /frontend-dist

      containers:
      # --- Contêiner da API (Gunicorn/Flask) ---
      - name: smart-remedy-api
        image: sevenleo/smart-remedy:latest
        imagePullPolicy: Always
        # O CMD do Dockerfile já é ["gunicorn", ...], então não precisamos de 'command'
        env:
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: admin-credentials
              key: ADMIN_USER
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: admin-credentials
              key: ADMIN_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: admin-credentials
              key: SECRET_KEY
        - name: FLASK_APP
          value: "wsgi:app"
        - name: FRONTEND_BASE_URL
          value: "https://smart-remedy.devops-master.shop"
        - name: JWT_EXPIRATION_HOURS
          value: "1"
        ports:
        - name: gunicorn
          containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            cpu: "256m"
            memory: "512Mi"
          limits:
            cpu: "512m"
            memory: "1Gi"
        volumeMounts:
        - name: smart-remedy-data
          mountPath: /app/data

      # --- Contêiner Sidecar do Nginx ---
      - name: smart-remedy-nginx
        image: nginx:1.25-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        # Monta a configuração customizada do Nginx
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        # Monta o volume com os arquivos estáticos do frontend
        - name: frontend-dist
          mountPath: /var/www/html
        readinessProbe:
          httpGet:
            path: /
            port: http
        livenessProbe:
          httpGet:
            path: /
            port: http
        resources:
          requests:
            cpu: "128m"
            memory: "128Mi"
          limits:
            cpu: "256m"
            memory: "256Mi"

      # --- Volume para a configuração do Nginx ---
      volumes:
      - name: nginx-config
        configMap:
          name: smart-remedy-nginx-conf

  volumeClaimTemplates:
  - metadata:
      name: smart-remedy-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 2Gi

---
# --- ConfigMap para a configuração do Nginx ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-remedy-nginx-conf
  namespace: smart-remedy
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    events {
        worker_connections 1024;
    }
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        access_log /dev/stdout;
        error_log /dev/stderr;
        sendfile on;
        keepalive_timeout 65;
        server {
            listen 80;
            location ~ ^/(api|admin|apidocs|flasgger_static|reports|docs)/ {
                proxy_pass http://127.0.0.1:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            location / {
                root /var/www/html;
                try_files $uri $uri/ /index.html;
            }
        }
    }

---
# --- Ingress: Expõe o serviço para o mundo externo ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smart-remedy-ingress
  namespace: smart-remedy
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: smart-remedy.devops-master.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smart-remedy
            port:
              number: 80