"""Autodetect database changes

Revision ID: 1367ea047777
Revises:
Create Date: 2025-10-30 21:35:52.945568

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1367ea047777"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("report_path", sa.String(length=512), nullable=False),
        sa.Column("json_summary_path", sa.String(length=512), nullable=False),
        sa.Column("date_range", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("json_summary_path"),
        sa.UniqueConstraint("report_path"),
    )
    op.create_table(
        "trend_analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("previous_report_id", sa.Integer(), nullable=False),
        sa.Column("current_report_id", sa.Integer(), nullable=False),
        sa.Column("trend_report_path", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_report_id"],
            ["report.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_report_id"],
            ["report.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("current_report_id"),
        sa.UniqueConstraint("trend_report_path"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trend_analysis")
    op.drop_table("report")
    # ### end Alembic commands ###
