# Workflow de CI/CD unificado: Testa, Constrói e Publica a imagem Docker.
name: CI - Build, Test, and Publish

on:
  # Dispara o workflow em pushes para as branches principais e de refatoração.
  push:
    # branches:
    #   - main
    #   - refactor/**
  # Dispara o workflow em pull requests para a branch main.
  pull_request:
    branches:
      - main
  # Permite a execução manual do workflow a partir da aba "Actions" do GitHub.
  workflow_dispatch:

jobs:
  build-test-publish:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código: Baixa o código do repositório para o runner.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configuração do Python: Prepara o ambiente Python.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Instalação de Dependências: Instala as bibliotecas listadas no requirements.txt.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Execução dos Testes: Roda a suíte de testes com pytest.
      # Se este passo falhar, o workflow para aqui.
      - name: Run tests
        run: pytest

      # 5. Check Code Formatting: Fails if code is not formatted with black.
      - name: Check code formatting
        run: black --check .

      # 5. Login no Docker Hub: Só executa em pushes para a branch 'main'.
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Build e Push da Imagem: Só executa em pushes para a 'main'.
      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/meu-dash-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/meu-dash-web:${{ github.sha }}