# Workflow de CI/CD unificado: Testa, Constrói e Publica a imagem Docker.
name: CI - Build, Test, and Publish

on:
  # Dispara o workflow em pushes para as branches principais e de refatoração.
  push:
    branches:
      - main
  # Dispara o workflow em pull requests para a branch main.
  pull_request:
    branches:
      - main
  # Permite a execução manual do workflow a partir da aba "Actions" do GitHub.
  workflow_dispatch:

jobs:
  build-test-publish:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código: Baixa o código do repositório para o runner.
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # Pinned to a specific commit
        with:
          fetch-depth: 0 # Realiza um clone completo, essencial para a resolução de caminhos

      # 2. Configuração dos Ambientes (Python e Node.js)
      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # Pinned to a specific commit
        with:
          python-version: '3.14'

      - name: Set up Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # 3. Cache e Instalação de Dependências
      - name: Cache pip dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Install Frontend Dependencies
        run: npm install --prefix frontend

      # 4. Validação do Backend
      - name: Check Backend Formatting
        run: ruff format --check backend

      - name: Lint Backend
        run: ruff check backend

      # - name: Run Backend Security Scan
      #   run: |
      #     pip install --upgrade bandit
      #     bandit -c pyproject.toml -r src -ll -ii
      #   working-directory: ./backend

      # - name: Run Backend Tests
      #   run: pytest
      #   working-directory: ./backend

      # 5. Validação do Frontend
      - name: Lint Frontend
        run: npm run lint --prefix frontend

      - name: Run Frontend Tests
        run: npm run test --prefix frontend

      # 6. Login no Docker Hub (apenas em push para 'main')
      - name: Log in to Docker Hub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # Pinned to a specific commit
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7. Build e Push da Imagem (apenas em push para 'main')
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # SHA do v2

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # SHA do v5
        with:
          platforms: linux/amd64
          context: . # O contexto do build deve ser a raiz do repositório
          file: ./Dockerfile # Especifica o caminho do Dockerfile na raiz
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/smart-remedy:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/smart-remedy:${{ github.sha }}